on:
  push:
    branches:
      - "*" # Matches all branches
  pull_request:
    branches:
      - "*" # Matches all branches for PR events

name: playwright.yaml

permissions: read-all

jobs:
  playwright:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: cd tests/playwright && npm ci

      - name: Install Playwright Browsers
        run: cd tests/playwright && npx playwright install --with-deps

      - name: Playwright tests
        run: cd tests/playwright && npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: tests/playwright/playwright-report/
          retention-days: 30